"""
Django settings for Fresh project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n$3crs-@^#6k8a2swnv0vx@v7w+!l&^qi#4j7dl@$hcvq8&-=q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'user',
    'rest_framework',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Fresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fresh.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static')

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CKEDITOR_UPLOAD_PATH = 'static/upload'
CKEDITOR_IMAGE_BACKEND = 'pillow'

APPID = "2016101000652497"

ALIPAY_PUBLIC_KEY_STRING = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz6mmwgohEIq7gpO/acdRire4AXe6GeohT13mRLWIYK+Gf/ezxT+GjG1DM6UJX+JKn1eUacpKBCMe83GxcTFXIdr4Np136TDJ7OcAbprs4csmUa/vw2bxQXBK6PYrYwblUAxN0HlpJh7kPwM7IKut9e/XDMorGLqTgBOI/dLCvfIdNU1jZ+ozppIo93fEGqTjC/HUis5EziyEHmZbnLJGGgufdiVA2H+HVL68sDUd1VpSWqHAE+HrH3sVwP80wR2zgcz47XYUK5/0h0m7QcW4jbqNEvMJ+CRHS7YLC/ucBwZrNGCyXTEXRx0h4mrz4FeAKyFPX0zy0ZY+pBRdTgOltQIDAQAB
-----END PUBLIC KEY-----"""

APP_PRIVATE_KEY_STRING = """-----BEGIN REA PRIVATE KEY-----
MIIEowIBAAKCAQEAz6mmwgohEIq7gpO/acdRire4AXe6GeohT13mRLWIYK+Gf/ezxT+GjG1DM6UJX+JKn1eUacpKBCMe83GxcTFXIdr4Np136TDJ7OcAbprs4csmUa/vw2bxQXBK6PYrYwblUAxN0HlpJh7kPwM7IKut9e/XDMorGLqTgBOI/dLCvfIdNU1jZ+ozppIo93fEGqTjC/HUis5EziyEHmZbnLJGGgufdiVA2H+HVL68sDUd1VpSWqHAE+HrH3sVwP80wR2zgcz47XYUK5/0h0m7QcW4jbqNEvMJ+CRHS7YLC/ucBwZrNGCyXTEXRx0h4mrz4FeAKyFPX0zy0ZY+pBRdTgOltQIDAQABAoIBAFqroYMhtxQo7vxxlGcUPzdJRk9lvl0oTEkCH9OqS5Sjrx9awSSDuzS/VFNNYQ17mcd/Du8uAylRSGdVIfvhZkEDAdOe58dqpRAKQLcKcBmagO2z2wU/gmFnLV4Qdhsz3JYZ+TPofw/E9zXILF30d+1lPkl4UF7owBRw8ySYjK0wKyiK/2YqGFxQOLdvbzqYzt14kHW7u67g+NeV5/zcHCze9yXVymVAgUGctE/Fjm1vdJf+dOWr5qa3SPkGzd8a95rnW2pDkOc51ck7Q+9uq+xSRNyJAsL4u66ENagwYPaIdMdGtQ/FfERcUQcL32n+zAf5zVcA/aH6qGWoFV+PAFUCgYEA8Hbc4FB4OmmXTD0j1/aktIfqGJosGg8SWZZYfUNjRD0aorm2Z+kBKkHbwEpEGoIDF12aY2PLr01PDu/ZtA8b4A0d4wlH2vtFkJ2bWHDXLXxSDUFMM0w+RXlc4qlctAp4ikbh6oOgvWXybTqJ6LRglm0oGh3Ng5xBuPZYgC/EW7MCgYEA3RRE+siPjfMoiHlgPFFOAsiQfR/8HCP8Aq3tJYc2JSE3/EE3Iumd4s/TO2l+jTBhIj9pB8koBmxxiug65z+Mg9fj8lnQ/e4ZRQeGmZ2C/Kjy5dYEyBbNkZr0EkHgciMQhP0H3Ne5l+yGAjw/ENO3O479GxbpATH7S/sUah2uJPcCgYBfvSNx1/gWYaYQf6M+v/+RtS96Ph/i/C81JgvzS5pBOAbb1Q8PzhBdr7z7kVYOK8dpTSZD/h7BnAknDE3kR8O0b+R/WVmXkUWAL5ADJWI2xPGyP1ZEck20wX4+7GlxcV3OyCv4gBHGdsmPvafc07xFCA7YXxdNGDB+oO5ZkysdywKBgQDK/qGX5DBsFqlRJqHGwKDwzVhei8/hxujPTQRDQTPmQ+o0JW2LERd3+3vpQaSB37pQyAiYrYui2lAnS7VKQH+1T7ZuASp0/vsU9yQQSSDM/hSKFUmur8FxwOX7HaIJK0kv02Y00aAIb5Vc2BTQTpYgidq91Pt9rXcg/RpxlW8hYQKBgAEdfsZdixuI6eXP2nNKcuhSawphWeq8k2uwcdv+owLHD2LoQLW3RC6kJtxhzQNvnGpXUb6Sui/QJjp3vJieEoedUQ8Kc5dne6oDKaRIQHu5VbyIzvqrgncTvYg92PpYXT688ERCyppHaDFlAYKjTIHLhsxcynxhR4hba/UcHHyN
-----END REA PRIVATE KEY-----"""

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}
