# Generated by Django 2.2 on 2019-07-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_goods_goods_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='商品种类')),
                ('description', models.TextField(verbose_name='商品类型描述')),
                ('logo', models.ImageField(upload_to='store/img', verbose_name='商品种类logo')),
            ],
            options={
                'verbose_name': '商品种类',
                'db_table': 'goodstype',
            },
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goodsimg',
            options={'verbose_name': '商品图片'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': '卖家'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店铺'},
        ),
        migrations.AlterModelOptions(
            name='storetype',
            options={'verbose_name': '店铺类型'},
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='goodsimg',
            table='goodsimg',
        ),
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
        migrations.AlterModelTable(
            name='storetype',
            table='storetype',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.GoodsType', verbose_name='商品类型'),
            preserve_default=False,
        ),
    ]
